### ISSUE TITLE
banana file decryption fail.

### ISSUE THREAD

**Issue by linkpad** [programa-stic/snapchat-decrypt#4]
Hello, I found out your project and it's very interesting, by the way I wanted to try it but I got an issue :

```
5.0.38.3
3d69435365438415

Traceback (most recent call last):
  File "D:\Users\Brandon\Desktop\snap decrypt\decrypt.py", line 140, in <module>
    decrypt_bananas_file()
  File "D:\Users\Brandon\Desktop\snap decrypt\decrypt.py", line 83, in decrypt_bananas_file
    decrypt_file(encrypted_bananas,decrypted_bananas,cipher )
  File "D:\Users\Brandon\Desktop\snap decrypt\decrypt.py", line 126, in decrypt_file
    chunk, next_chunk = next_chunk, cipher.decrypt(in_file.read(1024 * bs))
  File "C:\Python27\lib\site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

**Comment by TerrorFactor** [comment]
I have the same issue in 5.0.38.1. tried the latest version (9.x) and then downgraded to 5.0.38.3, then to 5.0.38.2 and then to 5.0.38.1, but I have the same issue on all 5.x versions.
I tried by sending new snaps to myself for every version, but no luck.

**Comment by xeroxnir** [comment]
Hi, have you tried doing it manually? Pulling the encrypted files from the internal memory then generating the md5 and decrypting "bananas1" file with aes.online-domain-tools.com? Did you Check that the "bananas" decrypted file makes any sense?

**Comment by justgettingstarted** [comment]
@zerokes is there no fix for decrypting files stored by v5.0.38.1. im also getting the same error as @linkpad!
