### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'encrypted_bananas_file'

### ISSUE THREAD

**Issue by abhishakemitra** [programa-stic/snapchat-decrypt#5]
Hi

This is the output I got when I tried the script. I have a rooted device.

8.0.0
Traceback (most recent call last):
  File "decrypt_photos.py", line 140, in <module>
    decrypt_bananas_file()
  File "decrypt_photos.py", line 80, in decrypt_bananas_file
    with open("encrypted_bananas_file") as encrypted_bananas:
IOError: [Errno 2] No such file or directory: 'encrypted_bananas_file'

**Comment by santimacia** [comment]
One short question, it works only with private messages or history images too?
